-- MySQL Script generated by MySQL Workbench
-- Wed May 12 20:14:46 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema service
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `service` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `service`.`mesa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`mesa` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `numero` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`comanda` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cod_mesa` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_mesa` (`cod_mesa` ASC) VISIBLE,
  CONSTRAINT `comanda_ibfk_1`
    FOREIGN KEY (`cod_mesa`)
    REFERENCES `service`.`mesa` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `mydb`.`fechamento_comanda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fechamento_comanda` (
  `idfechamento_comanda` INT NOT NULL,
  `comanda_id` BIGINT NOT NULL,
  `hora_de_fechamento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`idfechamento_comanda`),
  INDEX `fk_fechamento_comanda_comanda_idx` (`comanda_id` ASC) VISIBLE,
  CONSTRAINT `fk_fechamento_comanda_comanda`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `service`.`comanda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `service` ;

-- -----------------------------------------------------
-- Table `service`.`categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`categoria` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`usuario` (
  `codigo` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(50) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(150) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `service`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`produto` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(55) NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `cod_categoria` BIGINT NULL DEFAULT NULL,
  `valor` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_categoria` (`cod_categoria` ASC) VISIBLE,
  CONSTRAINT `produto_ibfk_1`
    FOREIGN KEY (`cod_categoria`)
    REFERENCES `service`.`categoria` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`pedido` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cod_mesa` BIGINT NOT NULL,
  `status` VARCHAR(15) NOT NULL,
  `hora_do_pedido` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `observacao` VARCHAR(255) NULL DEFAULT NULL,
  `cod_usuario` BIGINT NOT NULL,
  `comanda_id` BIGINT NOT NULL,
  `quantidade` INT NOT NULL,
  `produto_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_mesa` (`cod_mesa` ASC) VISIBLE,
  INDEX `cod_usuario` (`cod_usuario` ASC) VISIBLE,
  INDEX `fk_pedido_comanda1_idx` (`comanda_id` ASC) VISIBLE,
  INDEX `fk_pedido_produto1_idx` (`produto_id` ASC) VISIBLE,
  CONSTRAINT `pedido_ibfk_1`
    FOREIGN KEY (`cod_mesa`)
    REFERENCES `service`.`mesa` (`id`),
  CONSTRAINT `pedido_ibfk_2`
    FOREIGN KEY (`cod_usuario`)
    REFERENCES `service`.`usuario` (`codigo`),
  CONSTRAINT `fk_pedido_comanda1`
    FOREIGN KEY (`comanda_id`)
    REFERENCES `service`.`comanda` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_pedido_produto1`
    FOREIGN KEY (`produto_id`)
    REFERENCES `service`.`produto` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`cozinha`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`cozinha` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cod_pedido` BIGINT NOT NULL,
  `finalizado` ENUM('sim', 'nao') NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_pedido` (`cod_pedido` ASC) VISIBLE,
  CONSTRAINT `cozinha_ibfk_1`
    FOREIGN KEY (`cod_pedido`)
    REFERENCES `service`.`pedido` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`fechamento_pedido`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`fechamento_pedido` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `cod_pedido` BIGINT NULL DEFAULT NULL,
  `hora_de_fechamento` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `valor_total` DECIMAL(10,2) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `cod_pedido` (`cod_pedido` ASC) VISIBLE,
  CONSTRAINT `fechamento_pedido_ibfk_1`
    FOREIGN KEY (`cod_pedido`)
    REFERENCES `service`.`pedido` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`flyway_schema_history`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`flyway_schema_history` (
  `installed_rank` INT NOT NULL,
  `version` VARCHAR(50) NULL DEFAULT NULL,
  `description` VARCHAR(200) NOT NULL,
  `type` VARCHAR(20) NOT NULL,
  `script` VARCHAR(1000) NOT NULL,
  `checksum` INT NULL DEFAULT NULL,
  `installed_by` VARCHAR(100) NOT NULL,
  `installed_on` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `execution_time` INT NOT NULL,
  `success` TINYINT(1) NOT NULL,
  PRIMARY KEY (`installed_rank`),
  INDEX `flyway_schema_history_s_idx` (`success` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `service`.`permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`permissao` (
  `codigo` BIGINT NOT NULL,
  `descricao` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `service`.`usuario_permissao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `service`.`usuario_permissao` (
  `codigo_usuario` BIGINT NOT NULL,
  `codigo_permissao` BIGINT NOT NULL,
  PRIMARY KEY (`codigo_usuario`, `codigo_permissao`),
  INDEX `codigo_permissao` (`codigo_permissao` ASC) VISIBLE,
  CONSTRAINT `usuario_permissao_ibfk_1`
    FOREIGN KEY (`codigo_usuario`)
    REFERENCES `service`.`usuario` (`codigo`),
  CONSTRAINT `usuario_permissao_ibfk_2`
    FOREIGN KEY (`codigo_permissao`)
    REFERENCES `service`.`permissao` (`codigo`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
